### ISSUE TITLE
Ablegen der Dateien auf einem eigenen Webserver (nicht GitHub)

### ISSUE THREAD

**Issue by mojoaxel** [FreifunkFranken/freifunkfranken-community#2]
Es ist unschön, dass die Dateien nach jedem Update bie Git(Hub) eingecheckt werden.
Dadurch sind wir von github.com und rawgit.com abhängig-

Es wäre evtl. sinnvoll die Dateien auf einem Webserver abzulegen, wo sie auch aktuell gehalten werden. Dadurch, dass sich die Dateien [jederzeit neu erzeugen lassen](https://github.com/FreifunkFranken/community.franken.freifunk.net) müssen sie eigentlich garnicht eingechekt sein.

*Durch die Versionsverwaltung haben wir allerdings auch einen Überblick wie schnell unsere Community wächst (Historie).*

**Comment by kratz00** [comment]
* rawgit braucht man nicht unbedingt, siehe https://github.com/freifunk/directory.api.freifunk.net/blob/master/directory.json, da verwenden viele direkt GitHub (raw.githubusercontent.com), auch wenn dann nicht der richtig ContentType verwendet wird, *text/plain* anstatt *application/json* ist dies in diesem Anwendungsfall nicht relevant.
* GitHub laesst sich zur Not beliebig austauschen, Bitbucket etc. und du hast die gewuenschte Versionierung 

Ich sehe erst mal keinen zwingenden Grund etwas zu aendern :)

**Comment by kratz00** [comment]
Wenn https://github.com/freifunk/directory.api.freifunk.net/pull/200 Upstream ist,  bin ich dafuer dieses Ticket zu schliessen. Falls GitHub dicht macht, muessen wir uns ehe was einfallen lassen :)

**Comment by mojoaxel** [comment]
Ich glaube auch ohne den Wechsel zu gitusercontent.com können wir das hier zumachen. Falls github sich in Zukunft als unzuverlässig erweisen sollte müssen wir halt weiter sehen.
