### ISSUE TITLE
Verwendungszweck?

### ISSUE THREAD

**Issue by FunThomas424242** [FreifunkFranken/freifunkfranken-community#3]
Das die Dateien irgendwie die einzelnen Freifunk Gruppen beschreiben scheint mir offensichtlich aber wo spielt man die Teile später ein bzw. was kann man damit anfangen? Benutzt man diese beim Bau der Firmware? Helfen sie beim Aufsetzen eines FreifunkWikis für die lokale Gruppe oder wie funktioniert das?

**Comment by mojoaxel** [comment]
@FunThomas424242 Du hast ja viele Fragen! Also..
1. Die Dateien dienen der Beschreibung der einzelnen (Sub)-Communities von [http://franken.freifunk.net](Freifunk-Franken) in der [Freifunk-API](http://blog.freifunk.net/2013/die-neue-freifunk-api-aufruf-zum-mitmachen) und werden von dieser regelmäßig ausgelesen.
2. Die Dateien werden nciht zum Bau der Firmware verwendet sondern dienen momentan haupsächlich den Zweck einen Eintrag in der [Freifunk-Community-Map](http://freifunk.net/wie-mache-ich-mit/community-finden/) zu erzeugen.
3. Die Dateien hier werden durch ein [Skript](FreifunkFranken/community.franken.freifunk.net) generiert.
4. Den einzelnen Communities die Teil von Freifunk-Franken sind ist es möglich eigene Ansprechpartner usw. festzulegen.

**Comment by FunThomas424242** [comment]
Danke
