### ISSUE TITLE
Dokumentation: Verwendung der Community-Dateien 

### ISSUE THREAD

**Issue by kratz00** [FreifunkFranken/freifunkfranken-community#4]
Was ich im Moment noch nicht verstehe, was passiert mit den Community-Dateien nachdem diese hier eingecheckt wurden? Wer oder was verwendet diese und wie funktioniert dies technisch?

**Comment by mojoaxel** [comment]
duplicate of #3 !?

**Comment by kratz00** [comment]
Jop :)
Ich wuerde das Ticket offen lassen, damit ich die Infos mal in eine README schreiben kann, ok?
